language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
  - npm run build:demo
  - echo "$SFTP_KEY" | base64 --decode >/tmp/sftp_rsa
  - chmod +x deploy.demo.sh $SFTP_USER $SFTP_PASSWORD $SFTP_HOST $SFTP_PORT
  - ./deploy.demo.sh         
