language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
  - npm run build:demo
  - echo "$SFTP_KEY" | base64 --decode >/tmp/sftp_rsa
  - scp -P $SFTP_PORT -i /tmp/sftp_rsa -r dist/demo/* $SFTP_USER@$SFTP_HOST:~/public_html/react-virtualized-table-demo/